title: Tao Xu’s Blog
description: Notes
theme: minima
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Pages to show in the navigation bar
header_pages:
  - research.md
  - photos.md
  - finance.md
  - philosophy.md

# Theme information (optional, for descriptions)
themes:
  research:
    title: Academic
    blurb: Notes on mathematics, statistics
  photography:
    title: Photography
    blurb: Portfolio and shooting notes
