title: Tao Xu’s Blog
description: Notes on math, stats, philosophy, and life
theme: minima
# url: https://example.com   # <-- set this if you use a custom domain
# baseurl: ""                # <-- set this if you deploy under a subpath
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
